> ### **Assignment 2 - Numpy Array Operations** 

# Numpy and few of it's functions


### Matrix and vector products

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

- dot(a, b[, out])    
Dot product of two arrays.

- inner(a, b)     
Inner product of two arrays.

- outer(a, b[, out])     
Compute the outer product of two vectors.

- matmul(x1, x2, /[, out, casting, order, …])      
Matrix product of two arrays.

- kron(a, b)    
Kronecker product of two arrays.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations', privacy='secret', evironment=None)

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "rajibdasbhagat/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/rajibdasbhagat/numpy-array-operations


'https://jovian.ml/rajibdasbhagat/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 

function1 = np.dot(a, b)
function2 = np.inner(a, b)
function3 = np.outer(a, b)
function4 = np.matmul(a, b )
function5 = np.kron(a, b)


## Function 1 - np.dot

Returns dot product of two matrices.

In [6]:
# Example 1 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

The solution is the dot product of matrix a and matrix b.

In [7]:
# Example 2 
np.dot(b,a)
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 

The solution is the dot product of matrix b and matrix a.

In [8]:
# Example 3 
c=np.ones((2,2))
np.dot(a)

TypeError: dot() missing 1 required positional argument: 'b'

Explanation about example (why it breaks and how to fix it)\\
- Break reason: Provided only one arguuments.
- Solution: Requires two arguments, ie np.dot(a,c)

Use: to find dot product of two matrices.

In [9]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "rajibdasbhagat/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/rajibdasbhagat/numpy-array-operations


'https://jovian.ml/rajibdasbhagat/numpy-array-operations'

## Function 2 - np.inner

Returns inner product of two matrices.

In [10]:
# Example 1 - working
np.inner(a,b)

array([[35, 41],
       [81, 95]])

The solution is the inner product of matrix a and matrix b.

In [11]:
# Example 2 - working
np.inner(b,a)

array([[35, 81],
       [41, 95]])

The solution is the inner product of matrix b and matrix a.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
c=np.ones((2,2))
np.inner(a)

TypeError: inner() missing 1 required positional argument: 'b'

Explanation about example (why it breaks and how to fix it)
- Break reason: Provided only one arguuments.
- Solution: Requires two arguments, ie np.inner(a,c)

Usage: To find inner product of two matrices.

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "rajibdasbhagat/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/rajibdasbhagat/numpy-array-operations


'https://jovian.ml/rajibdasbhagat/numpy-array-operations'

## Function 3 - np.outer

Returns outer product of two matrices.

In [14]:
# Example 1 - working
np.outer(a,b)

array([[11, 12, 13, 14],
       [22, 24, 26, 28],
       [33, 36, 39, 42],
       [44, 48, 52, 56]])

The solution is the outer product of matrix a and matrix b.

In [15]:
# Example 2 - working
np.outer(b,a)

array([[11, 22, 33, 44],
       [12, 24, 36, 48],
       [13, 26, 39, 52],
       [14, 28, 42, 56]])

The solution is the outer product of matrix b and matrix a.

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
c=np.ones((2,2))
np.outer(a)

TypeError: _outer_dispatcher() missing 1 required positional argument: 'b'

Explanation about example (why it breaks and how to fix it)
- Break reason: Provided only one arguuments.
- Solution: Requires two arguments, ie np.outer(a,c)

Usage: To find outer product of two matrices.

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "rajibdasbhagat/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/rajibdasbhagat/numpy-array-operations


'https://jovian.ml/rajibdasbhagat/numpy-array-operations'

## Function 4 - np.matmul

Computes matrix product of two matrices.

In [18]:
# Example 1 - working
np.matmul(a,b)

array([[37, 40],
       [85, 92]])

The solution is the product/multiplication of matrix a and matrix b.

In [19]:
# Example 2 - working
np.matmul(b,a)

array([[47, 70],
       [55, 82]])

The solution is the product/multiplication of matrix b and matrix a.

In [20]:
# Example 3 - breaking (to illustrate when it breaks)
c=np.ones((2,2))
np.matmul(a)

ValueError: invalid number of arguments

Explanation about example (why it breaks and how to fix it)
- Break reason: Provided only one arguuments.
- Solution: Requires two arguments, ie np.matmul(a,c)

Usage: To calculate product of two matrices.

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "rajibdasbhagat/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/rajibdasbhagat/numpy-array-operations


'https://jovian.ml/rajibdasbhagat/numpy-array-operations'

## Function 5 - np.kron

Computes kronecker product of two arrays

In [22]:
# Example 1 - working
np.kron(a,b)

array([[11, 12, 22, 24],
       [13, 14, 26, 28],
       [33, 36, 44, 48],
       [39, 42, 52, 56]])

The solution is the Kronecker product of matrix a and matrix b.

In [23]:
# Example 2 - working
np.kron(b,a)

array([[11, 22, 12, 24],
       [33, 44, 36, 48],
       [13, 26, 14, 28],
       [39, 52, 42, 56]])

The solution is the Kronecker product of matrix b and matrix a.

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
c=np.ones((2,2))
np.kron(a)

TypeError: _kron_dispatcher() missing 1 required positional argument: 'b'

Explanation about example (why it breaks and how to fix it)
- Break reason: Provided only one arguuments.
- Solution: Requires two arguments, ie np.kron(a,c)

Usage: To calculate Kronecker product of two matrices.

In [25]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "rajibdasbhagat/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/rajibdasbhagat/numpy-array-operations


'https://jovian.ml/rajibdasbhagat/numpy-array-operations'

## Conclusion

This notebook emphazized on few basic and simple usage of matrix and its products.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
