# Introduction to PyTorch and Tensor Operations.

A PyTorch Tensor is basically similar to a numpy array. PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.

A Tensor is an n-dimensional array, and it provides many functions for operating on these Tensors. Main take away is that Tensors can keep track of a computational graph and gradients, but they’re also useful as a generic tool for scientific computing, while numpy is slow and can't be used for back-propogation and updation of required matrices.

Few of the tensor functions are provided below: 

- tensor()
- view()
- permute()
- flatten()
- item() 

Before we begin, let's install and import PyTorch

In [ ]:
# installation for Windows
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html


Looking in links: https://download.pytorch.org/whl/torch_stable.html


In [2]:
# Import torch and other required modules
import torch
import numpy as np
import jovian

## Function 1 - torch.tensor()

A tensor can be constructed from a Python list or sequence using the torch.tensor() constructor. torch.Tensor is an alias for the default tensor type (torch.FloatTensor).


In [3]:
# Example 1 - working 
arr1 = [[1.,2 ,3, 4],
        [5 ,6 ,7, 8],
        [9, 10, 11, 12 ]]
#print(arr1)        
np_arr = np.array(arr1)
#print(np_arr)
ex1 = torch.tensor(np_arr)
ex1 

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)

Returns a non-empty tensor which is transformed from matrix to numpy array and then to tensor.

In [4]:
# Example 2 - working
ex2 = torch.tensor(arr1)
ex2        

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

Returns a non-empty tensor from a matrix which is converted to tensor.

In [5]:
# Example 3 - breaking (to illustrate when it breaks)
arr2 = [[1.,2 ,3],
        [5 ,6 ],
        [9, 10, 11, 12 ]]
ex3 = torch.tensor(arr2)
ex3 

ValueError: ignored

In the given arr3, at dim 1 the length is 3, other dim is expected to be length 3, but found 2. Diminsion mis-match.

**Usage: to create a tensor from a matrix or numpy matrix.** 

## Function 2 - view() 

PyTorch allows a tensor to be a view of an existing tensor. View tensor shares the same underlying data with its base tensor. Supporting view avoids explicit data copy, thus allows us to do fast and memory efficient reshaping, slicing and element-wise operations.

In [6]:
# Example 1 - working
ex1.view(6,2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]], dtype=torch.float64)

Returns the reshaped tensor with 2-diminsion shape 6 x 2.

In [7]:
# Example 2 - working
ex1.view(2,3,2)

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]], dtype=torch.float64)

Returns the reshaped tensor with 3-diminsion shape 2 x 3 x 2.

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
ex1.view()

TypeError: ignored

view() requires 1 positional arguments: "size". Such as for arr1 shape 4 X 3; all valid size are (12), (4,3), (2,2,3) etc. 

**Usage: reshaping, slicing and element-wise operations.**

## Function 3 - permute()

Returns a view of the original tensor with its dimensions permuted.

In [ ]:
# Example 1 - working
arr3=[[1,2,3,4,5,6],
     [11,12,4,5,6,13],
     [21,4,5,6,22,23],
     [11,12,4,5,6,13]]
arr4 = torch.tensor(arr3)     
arr4.permute(-2,1)

tensor([[ 1,  2,  3,  4,  5,  6],
        [11, 12,  4,  5,  6, 13],
        [21,  4,  5,  6, 22, 23],
        [11, 12,  4,  5,  6, 13]])

The positional argument in permute(-2,1), permute(0,1) shows the original array. 

In [ ]:
# Example 2 - working     
arr5 = arr4.permute(1,0)
arr5

tensor([[ 1, 11, 21, 11],
        [ 2, 12,  4, 12],
        [ 3,  4,  5,  4],
        [ 4,  5,  6,  5],
        [ 5,  6, 22,  6],
        [ 6, 13, 23, 13]])

The positional argument in permute(-1,0), permute(1,0) changes the shape of the array.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr5.permute()

TypeError: ignored

The function permute() requires 1 positional arguments: "dims". The dims must be in the range(-2,1).

**Usage: to swap the axes or to transpose a matrix.** 

## Function 4 - item()

Returns a Python number from a tensor containing a single value.

Add some explanations

In [ ]:
# Example 1 - working
arr5[0][0].item()

1

Explanation about example

In [ ]:
# Example 2 - working
c = torch.tensor([1, 2, 3, 4])
c[0].item()

1

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
c.item()

ValueError: ignored

Only one element tensors can be converted to Python scalars.

**Usage: to fetch only one required item from the tensors.** 

## Function 5 - flatten()

Flattens a contiguous range of diminesions in a tensor similar to 1-d array.

In [ ]:
# Example 1 - working
print(arr5)
torch.flatten(arr5)

tensor([[ 1, 11, 21, 11],
        [ 2, 12,  4, 12],
        [ 3,  4,  5,  4],
        [ 4,  5,  6,  5],
        [ 5,  6, 22,  6],
        [ 6, 13, 23, 13]])


tensor([ 1, 11, 21, 11,  2, 12,  4, 12,  3,  4,  5,  4,  4,  5,  6,  5,  5,  6,
        22,  6,  6, 13, 23, 13])

Removes all of the dimensions except for one.

In [ ]:
# Example 2 - working
print(ex1)
torch.flatten(ex1)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       dtype=torch.float64)

Removes all of the dimensions except for one.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
print(arr1)
torch.flatten(arr1)

[[1.0, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


TypeError: ignored

flatten() argument requires 'input' (position 1) as Tensor, not list.

**Usage: A flatten operation on a tensor reshapes the tensor to have a shape that is equal to the number of elements contained in the tensor. This is the same thing as a 1d-array of elements.** 

## Conclusion

From this notebook, one is able to understand what tensor is and what is the difference between the usage of numpy and tensor. 

The functions with examples as elastrated above shows the usage and the necessarity when as required.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* Stack Overflow: https://stackoverflow.com/
* Deeplizard: https://deeplizard.com/ 

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: 